apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-secretstore-uat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/iahmad-khan/infrastructure-as-code
    targetRevision: HEAD
    path: vault-eso/eso/secretstore
    directory:
      include: "uat.yaml"
  destination:
    name: uat
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
