apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-uat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "0.9.13"
      helm:
        valueFiles:
          - $values/vault-eso/eso/values/base.yaml
          - $values/vault-eso/eso/values/uat.yaml
    - repoURL: https://github.com/iahmad-khan/infrastructure-as-code
      targetRevision: HEAD
      ref: values
  destination:
    name: uat
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
