{{- if .Values.apps.envoyGateway.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-{{ .Values.env }}
  namespace: {{ .Values.argoCDNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.apps.envoyGateway.syncWave | quote }}
spec:
  project: default
  sources:
    - repoURL: https://charts.gateway.envoyproxy.io
      chart: gateway-helm
      targetRevision: {{ .Values.apps.envoyGateway.chartVersion | quote }}
      helm:
        valueFiles:
          - $values/vault-eso/argocd/app-default-values/envoy-gateway/values/base.yaml
          - $values/vault-eso/argocd/environments/{{ .Values.env }}/envoy-gateway/values.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    name: {{ .Values.env }}
    namespace: {{ .Values.apps.envoyGateway.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
