apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
  annotations:
    # Deploy after ESO and the vault-backend SecretStore are ready
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/iahmad-khan/infrastructure-as-code
    targetRevision: HEAD
    path: vault-eso/hello-world
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    name: dev
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
